"""add comments to report

Revision ID: 026f2438142a
Revises: b1243ac6a0b8
Create Date: 2025-08-26 12:42:35.196591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026f2438142a'
down_revision = 'b1243ac6a0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
