"""add sell and purchase price in drugs table

Revision ID: 2a6257c8b915
Revises: 4f0076de1614
Create Date: 2025-06-26 08:51:52.023399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6257c8b915'
down_revision = '4f0076de1614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('sell_price')
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###
