"""Make pharmacy_id column in product

Revision ID: 82c63466deea
Revises: a68f6787606f
Create Date: 2025-08-15 14:26:26.516288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c63466deea'
down_revision = 'a68f6787606f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Pharmacy_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pharmacy', ['Pharmacy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Pharmacy_id')

    # ### end Alembic commands ###
