"""Modify product table

Revision ID: 890090e6048b
Revises: 82c63466deea
Create Date: 2025-08-15 14:50:47.779203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890090e6048b'
down_revision = '82c63466deea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('product_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('product_shelf_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('product_Pharmacy_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pharmacy', ['pharmacy_id'], ['id'])
        batch_op.drop_column('Pharmacy_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Pharmacy_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_Pharmacy_id_fkey'), 'pharmacy', ['Pharmacy_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('product_shelf_number_key'), ['shelf_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('product_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('pharmacy_id')

    # ### end Alembic commands ###
