"""Modify timing method

Revision ID: b1243ac6a0b8
Revises: 890090e6048b
Create Date: 2025-08-15 14:55:33.254181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1243ac6a0b8'
down_revision = '890090e6048b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
