"""add pharmcy to sale_2

Revision ID: e96625f975a3
Revises: 026f2438142a
Create Date: 2025-09-08 08:19:37.959632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96625f975a3'
down_revision = '026f2438142a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pharmacy', ['pharmacy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    # ### end Alembic commands ###
